# 需要在本机 hosts 文件上加 127.0.0.1 es.com kibana.com
# 需要安装 ingress 链接为: [https://kubernetes.github.io/ingress-nginx/deploy/]
# pod
apiVersion: v1
kind: Pod
metadata:
  name: es
  labels:
    app: es
spec:
  containers:
  - image: "elasticsearch:8.8.1"
    imagePullPolicy: IfNotPresent
    name: es
    env:
    - name: ES_JAVA_OPTS
      value: "-Xms2048m -Xmx2048m"
    - name: discovery.type
      value: "single-node"
    ports:
    - containerPort: 9200
    resources:
      requests:
        memory: 1024Mi
        cpu: 300m
      limits:
        memory: 4096Mi
        cpu: 600m
  volumes:
  - name: data
    emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: es-kibana
  labels:
    app: es-kibana
spec:
  containers:
  - image: "kibana:8.8.1"
    imagePullPolicy: IfNotPresent
    name: es-kibana
    ports:
    - containerPort: 5601
    resources:
      requests:
        memory: 1024Mi
        cpu: 300m
      limits:
        memory: 2048Mi
        cpu: 600m
    env:
    - name: ELASTICSEARCH_URL
      value: "http://es.com"
  volumes:
  - name: data
    emptyDir: {}
---
# service
apiVersion: v1
kind: Service
metadata:
  name: es-kibana-svc
  labels:
    app: es-kibana
spec:
  selector:
    app: es-kibana
  ports:
  - port: 5601
    targetPort: 5601
---
# service
apiVersion: v1
kind: Service
metadata:
  name: es-svc
  labels:
    app: es
spec:
  selector:
    app: es
  ports:
  - port: 9200
    targetPort: 9200
---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: es-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: kibana.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: es-kibana-svc
            port:
              number: 5601
  - host: es.com           
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: es-svc
            port:
              number: 9200
